//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SR1PlayaCustomizer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceGameFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceGameFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SR1PlayaCustomizer.ResourceGameFiles", typeof(ResourceGameFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;&lt;Table&gt;&lt;Defaults&gt;&lt;Name&gt;Defaults&lt;/Name&gt;&lt;Defaults_List&gt;.
        /// </summary>
        public static string CUSTOMIZATION_DEFAULT_ITEMS_PREFIX {
            get {
                return ResourceManager.GetString("CUSTOMIZATION_DEFAULT_ITEMS_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/Defaults_List&gt;&lt;_Editor&gt;&lt;Category&gt;Entries&lt;/Category&gt;&lt;/_Editor&gt;&lt;/Defaults&gt;&lt;/Table&gt;&lt;TableTemplates&gt;&lt;/TableTemplates&gt;&lt;TableDescription&gt;&lt;Name&gt;Defaults&lt;/Name&gt;&lt;Type&gt;TableDescription&lt;/Type&gt;&lt;Element&gt;&lt;Name&gt;Name&lt;/Name&gt;&lt;Type&gt;String&lt;/Type&gt;&lt;/Element&gt;&lt;Element&gt;&lt;Name&gt;Defaults_List&lt;/Name&gt;&lt;Type&gt;Grid&lt;/Type&gt;&lt;Display_Name&gt;Defaults List&lt;/Display_Name&gt;&lt;Element&gt;&lt;Name&gt;Default&lt;/Name&gt;&lt;Type&gt;Element&lt;/Type&gt;&lt;Element&gt;&lt;Name&gt;Item&lt;/Name&gt;&lt;Type&gt;Reference&lt;/Type&gt;&lt;Description&gt;Default item that the PC will wear.&lt;/Description&gt;&lt;Reference&gt;&lt;File&gt;cust [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CUSTOMIZATION_DEFAULT_ITEMS_SUFFIX {
            get {
                return ResourceManager.GetString("CUSTOMIZATION_DEFAULT_ITEMS_SUFFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] customization_items {
            get {
                object obj = ResourceManager.GetObject("customization_items", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_creation {
            get {
                object obj = ResourceManager.GetObject("player_creation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_creation_hair {
            get {
                object obj = ResourceManager.GetObject("player_creation_hair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_creation_hair_color {
            get {
                object obj = ResourceManager.GetObject("player_creation_hair_color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] player_presets {
            get {
                object obj = ResourceManager.GetObject("player_presets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;&lt;Table&gt;&lt;Preset&gt;&lt;Name&gt;white1&lt;/Name&gt;&lt;DisplayName&gt;MAINMENU_MULTI&lt;/DisplayName&gt;&lt;Preset_Grid&gt;.
        /// </summary>
        public static string PLAYER_PRESETS_PREFIX {
            get {
                return ResourceManager.GetString("PLAYER_PRESETS_PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/Preset_Grid&gt;&lt;/Preset&gt;&lt;Preset&gt;&lt;Name&gt;white2&lt;/Name&gt;&lt;DisplayName&gt;PLAYER_CREATION_PRESET_WHITE&lt;/DisplayName&gt;&lt;Preset_Grid&gt;&lt;Preset_Element&gt;&lt;Morph_Name&gt;brow height&lt;/Morph_Name&gt;&lt;Value&gt;0.25&lt;/Value&gt;&lt;/Preset_Element&gt;&lt;Preset_Element&gt;&lt;Morph_Name&gt;eye depth&lt;/Morph_Name&gt;&lt;Value&gt;0.4375&lt;/Value&gt;&lt;/Preset_Element&gt;&lt;Preset_Element&gt;&lt;Morph_Name&gt;eyelid shape&lt;/Morph_Name&gt;&lt;Value&gt;0.25&lt;/Value&gt;&lt;/Preset_Element&gt;&lt;Preset_Element&gt;&lt;Morph_Name&gt;eyelid slant&lt;/Morph_Name&gt;&lt;Value&gt;0.406&lt;/Value&gt;&lt;/Preset_Element&gt;&lt;Preset_Element&gt;&lt;Morph_Name&gt;eyelid look [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PLAYER_PRESETS_SUFFIX {
            get {
                return ResourceManager.GetString("PLAYER_PRESETS_SUFFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BINTEXT
        ///
        ///ak47=K6 Krukov
        ///beretta=VICE 9
        ///charge_launcher=Charge Launcher
        ///desert eagle=GDHC .50
        ///glock=NR4
        ///m16=AR-40 Xtnd
        ///mac10=SKR-7 Spree
        ///magnum=.44 Shepherd
        ///pcp=PCP
        ///pump_action_shotgun=Tombstone
        ///rpg_launcher=RPG Launcher
        ///spas12=AS12 Riot
        ///stun_gun=Stun Gun
        ///tec9=T3K Urban
        ///twelve_gauge=12 Gauge
        ///baseball_bat=Baseball Bat
        ///camera=Camera
        ///cellphone=Cellphone
        ///grenade=Hand Grenade
        ///knife=Knife
        ///molotov=Molotov Cocktail
        ///nightstick=Nightstick
        ///pimp_slap=Pimp Slap
        ///pipe_bomb=Pipe Bomb
        ///sniper_rifle=M [rest of string was truncated]&quot;;.
        /// </summary>
        public static string US_Strings {
            get {
                return ResourceManager.GetString("US_Strings", resourceCulture);
            }
        }
    }
}
